# $FreeBSD$

PORTNAME=	uhidvkbdd
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://althenia.net/files/

MAINTAINER=	aaz@q-fu.com
COMMENT=	Driver for USB media keys

LICENSE=	BSD2CLAUSE

PLIST_FILES=	sbin/uhidvkbdd \
		etc/rc.d/uhidvkbdd \
		etc/devd/uhidvkbdd.conf \
		man/man8/uhidvkbdd.8.gz

.include <bsd.port.mk>
